name: Deploy Next.js app to Azure Web App - alma4dashname: Deploy Next.js app to Azure      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_90E427DC40B14D62B4856B70B6E489AF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3DD2A63434FE40BBBE27FB7E9723BF9B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_019BFA850FAD45DCB1FFB3C9956EC255 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: alma4dash
          package: .

on:
  push:
    branches:
